Repository Intel-Media-SDK/MediaSDK, pull requests merged in 2018-06, with the labels that each got.

#251 [SW BRC] Fix for buffer overflow
  _studio/mfx_lib/shared/src/mfx_brc_common.cpp
  samples/sample_common/src/brc_routines.cpp
Labels: Rebase needed

#252 [h264d] Prevent crop info to be printed in sample_decode
  _studio/shared/umc/codec/h264_dec/src/umc_h264_mfx_supplier.cpp
Labels: Rebase needed

#258 Document direct cmake configure build in README
  README.md
Labels: documentation

#260 [AVCe] Add missing checks of libva return statuses to AVC encoder
  _studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h
  _studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
Labels: Rebase needed

#233 add rounding offset support for sample encode
  samples/sample_encode/include/pipeline_encode.h
  samples/sample_encode/src/pipeline_encode.cpp
  samples/sample_encode/src/sample_encode.cpp
Labels: Rebase needed

#289 Fix a wrong VAAPI check in FillCUQPDataDDI
  _studio/hevce_hw/h265/src/mfx_h265_encode_hw_ddi.cpp
Labels: help wanted

#136 [hevce] Enabled LowPower mode on CNL
  _studio/hevce_hw/h265/include/mfx_h265_encode_vaapi.h
Labels: Rebase needed
